### ISSUE TITLE
Add gnome-terminal to the list of requirements in the README

### ISSUE THREAD

**Issue by Ligh7bringer** [acsbendi/Build-SFML-For-Android-On-Linux#1]
Since the scripts depend on ```gnome-terminal```, it should probably be added as a requirement.

**Comment by acsbendi** [comment]
Yes, you're right, thanks for letting me know. I think I'll rework it a bit so that it will be an optional requirement, and only use it when it's available.

**Comment by acsbendi** [comment]
@Ligh7bringer It should be fixed now :) Do you know of a command to open a new terminal on your system? Can you use `xterm`? I would add it to enable parallel builds.

**Comment by Ligh7bringer** [comment]
How about not depending on terminals at all? You could run the commands in parallel without the need for separate terminal tabs:
```
# define commands
cmd="ls"                                                                                                  
cmd2="uname -a"

# run them, '&' runs them in parallel
$cmd &
$cmd2 &                                                                                                        

# wait for them to finish 
wait   
```

**Comment by acsbendi** [comment]
@Ligh7bringer I'd rather have a separate terminal for each building process so that I can see any errors separately. It might be confusing if all of the building processes use the same terminal for logging at the same time.
